name: Auto Add Issues to Project

on:
  issues:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    name: Assign to One Project
    runs-on: ubuntu-latest
    steps:
      - name: Assign new issues to project 
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: https://github.com/orgs/Rivnam-Manvir/projects/2